{"name": "Тест получения заказа пользователя без авторизации", "status": "passed", "description": "Получение ошибки при попытке получить инфо о заказе без авторизации", "start": 1718628631095, "stop": 1718628631358, "uuid": "a92ccc54-917a-4c6c-9af9-ea6a5f10f9f1", "historyId": "dc6b5b7f88d5637c7c3efcd603b1dc6b", "testCaseId": "dc6b5b7f88d5637c7c3efcd603b1dc6b", "fullName": "tests.test_api_get_user_orders.TestApiGetUserOrders#test_no_auth_user_get_user_order_error", "labels": [{"name": "feature", "value": "Проверка получения заказа конкретного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_get_user_orders"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "19588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_get_user_orders"}]}